language: node_js
node_js:
  - "5"

branches:
  only:
    - master
    - develop

script:
  - echo 'deb http://www.rabbitmq.com/debian/ testing main' |
        tee /etc/apt/sources.list.d/rabbitmq.list
  - wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc |
      apt-key add -
  - apt-get update
  - apt-get install rabbitmq-server -y
  - nohup rabbitmq-server &
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage